// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcd2Ysn8n1IhQ9DlHqVMBtfFUNmr9rhAE',
    appId: '1:91634135590:web:c3d5dfd170538094e6ace7',
    messagingSenderId: '91634135590',
    projectId: 'testapp-f9978',
    authDomain: 'testapp-f9978.firebaseapp.com',
    storageBucket: 'testapp-f9978.appspot.com',
    measurementId: 'G-G4QF6VWDXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTV4aWJ6EbtB1x83ui_s9zHDKpaXcut0',
    appId: '1:91634135590:android:e4459e7e611e0143e6ace7',
    messagingSenderId: '91634135590',
    projectId: 'testapp-f9978',
    storageBucket: 'testapp-f9978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb7AYT98Sll2AGfCvsr7IpHIKrRtl-QWU',
    appId: '1:91634135590:ios:4bf009a3a7b25c6fe6ace7',
    messagingSenderId: '91634135590',
    projectId: 'testapp-f9978',
    storageBucket: 'testapp-f9978.appspot.com',
    iosClientId: '91634135590-sr6i1olk4oasv2d2p8b89atms6c02hqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
